# Generated by Django 4.1.4 on 2022-12-19 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AirlineTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('boarding_till', models.IntegerField(choices=[(1, '00:00'), (13, '06:00'), (25, '12:00'), (37, '18:00'), (2, '00:30'), (14, '06:30'), (26, '12:30'), (38, '18:30'), (3, '01:00'), (15, '07:00'), (27, '13:00'), (39, '19:00'), (4, '01:30'), (16, '07:30'), (28, '13:30'), (40, '19:30'), (5, '02:00'), (17, '08:00'), (29, '14:00'), (41, '20:00'), (6, '02:30'), (18, '08:30'), (30, '14:30'), (42, '20:30'), (7, '03:00'), (19, '09:00'), (31, '15:00'), (43, '21:00'), (8, '03:30'), (20, '09:30'), (32, '15:30'), (44, '21:30'), (9, '04:00'), (21, '10:00'), (33, '16:00'), (45, '22:00'), (10, '04:30'), (22, '10:30'), (34, '16:30'), (46, '22:30'), (11, '05:00'), (23, '11:00'), (35, '17:00'), (47, '23:00'), (12, '05:30'), (24, '11:30'), (36, '17:30'), (48, '23:30')])),
                ('depart_time', models.IntegerField(choices=[(1, '00:00'), (13, '06:00'), (25, '12:00'), (37, '18:00'), (2, '00:30'), (14, '06:30'), (26, '12:30'), (38, '18:30'), (3, '01:00'), (15, '07:00'), (27, '13:00'), (39, '19:00'), (4, '01:30'), (16, '07:30'), (28, '13:30'), (40, '19:30'), (5, '02:00'), (17, '08:00'), (29, '14:00'), (41, '20:00'), (6, '02:30'), (18, '08:30'), (30, '14:30'), (42, '20:30'), (7, '03:00'), (19, '09:00'), (31, '15:00'), (43, '21:00'), (8, '03:30'), (20, '09:30'), (32, '15:30'), (44, '21:30'), (9, '04:00'), (21, '10:00'), (33, '16:00'), (45, '22:00'), (10, '04:30'), (22, '10:30'), (34, '16:30'), (46, '22:30'), (11, '05:00'), (23, '11:00'), (35, '17:00'), (47, '23:00'), (12, '05:30'), (24, '11:30'), (36, '17:30'), (48, '23:30')])),
                ('arrive_time', models.IntegerField(choices=[(1, '00:00'), (13, '06:00'), (25, '12:00'), (37, '18:00'), (2, '00:30'), (14, '06:30'), (26, '12:30'), (38, '18:30'), (3, '01:00'), (15, '07:00'), (27, '13:00'), (39, '19:00'), (4, '01:30'), (16, '07:30'), (28, '13:30'), (40, '19:30'), (5, '02:00'), (17, '08:00'), (29, '14:00'), (41, '20:00'), (6, '02:30'), (18, '08:30'), (30, '14:30'), (42, '20:30'), (7, '03:00'), (19, '09:00'), (31, '15:00'), (43, '21:00'), (8, '03:30'), (20, '09:30'), (32, '15:30'), (44, '21:30'), (9, '04:00'), (21, '10:00'), (33, '16:00'), (45, '22:00'), (10, '04:30'), (22, '10:30'), (34, '16:30'), (46, '22:30'), (11, '05:00'), (23, '11:00'), (35, '17:00'), (47, '23:00'), (12, '05:30'), (24, '11:30'), (36, '17:30'), (48, '23:30')])),
                ('gate', models.CharField(max_length=10)),
                ('flight', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportations', to='transportation.companies')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AirlineTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.CharField(max_length=10)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='transportation.airlinetransport')),
            ],
        ),
    ]
