# Generated by Django 4.1.4 on 2022-12-14 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractResidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('capacity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('map_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='VillaResidence',
            fields=[
                ('abstractresidence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='residence.abstractresidence')),
            ],
            bases=('residence.abstractresidence',),
        ),
        migrations.CreateModel(
            name='ResidenceAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='residences/avatars')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='residence.abstractresidence')),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('description', models.TextField()),
                ('location', models.ManyToManyField(to='residence.locations')),
            ],
        ),
        migrations.CreateModel(
            name='HotelAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotels/avatars')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='residence.hotels')),
            ],
        ),
        migrations.AddField(
            model_name='abstractresidence',
            name='facilities',
            field=models.ManyToManyField(to='residence.facilities'),
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('abstractresidence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='residence.abstractresidence')),
                ('room_number', models.CharField(max_length=10)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='residence.hotels')),
            ],
            bases=('residence.abstractresidence',),
        ),
    ]
